### ISSUE TITLE
Extension of the address areas in the PDF header

### ISSUE THREAD

**Issue by swinde** [OXIDprojects/pdf-invoice-module#12]
I would like to suggest extending the address areas in the PDF header by one field each.
At the payment address "oxbilladdinfo" and the delivery address "oxdeladdinfo".

For example, this field is used by the customers when delivering to a packing station to provide the necessary mailing number.

I apologize for my Google English!

**Comment by ivoba** [comment]
Thanks for your suggestions.
You can provide a PR for this change, if you like.

**Comment by swinde** [comment]
Thank you for your response!
Should the pull request be made in the master branch or in a new branch?

**Comment by ivoba** [comment]
You can create the change in a branch on your fork and request the change against the master branch of the original repo.
