### ISSUE TITLE
protected function _setPaymentInfo (& $ iStartPos) calls the wrong ConfigParameter 'blShowVATForDelivery'

### ISSUE THREAD

**Issue by swinde** [OXIDprojects/pdf-invoice-module#27]
The protected function _setPaymentInfo (& $ iStartPos) calls the wrong ConfigParameter 'blShowVATForDelivery'!
Correct, in my opinion, would be 'blShowVATForPayCharge'.

**Comment by swinde** [comment]
In the case of a negative payment method price (-3% discount), no invoice will be issued.

**Comment by ivoba** [comment]
merged and released in 2.2.1
