### ISSUE TITLE
pdf generation fails when using child theme -> missing pdf_logo.jpg

### ISSUE THREAD

**Issue by michaelkeiluweit** [OXIDprojects/pdf-invoice-module#7]
pdf generation of invoices fails. i have a child template. within this child template i have a directory called img but no changes to the logo img so no upload within this directory. seems like fallback to parent theme isn't working correctly.

2011/09/08 12:51:14 [error] 27791#0: *18 FastCGI sent in stderr: "PHP Warning: getimagesize(/srv/www/xxx/out/childtheme/img//pdf_logo.jpg): failed to open stream: No such file or directory in /srv/www/xxx/modules/invoicepdf/myorder.php on line 747" while reading response header from upstream, client: 213.61.xxx.xxx, server: shop.xxx.de, request: "POST /admin/index.php?editlanguage=0&stoken=B76C8213& HTTP/1.1", upstream:

**Comment by michaelkeiluweit** [comment]
Moved from Shop bugtracker to the project issue tracker.
https://bugs.oxid-esales.com/view.php?id=3235

**Comment by ivoba** [comment]
Fixed in #8
